name: OSX

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:               
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          mkdir release
          python scripts/mk_make.py --prefix=$PWD/release --java
          cd build
          make -j $(nproc)
          make install 
      - uses: actions/upload-artifact@v4
        with:
          name: osx-build
          path: release/
