name: Release

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:               
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}-${{ github.run_id }}
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ github.token }}


  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - run: |
          python scripts/mk_make.py -x --java
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          nmake
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/
      - name: upload libz3legacy.dll
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/libz3legacy.dll
          asset_name: libz3legacy.dll
          asset_content_type: application/binary
      - name: upload libz3javalegacy.dll
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/z3javalegacy.dll
          asset_name: libz3javalegacy.dll
          asset_content_type: application/binary
  

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-action
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/
      - name: upload libz3legacy.so
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/libz3legacy.so
          asset_name: libz3legacy.so
          asset_content_type: application/binary
      - name: upload libz3javalegacy.so
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/libz3javalegacy.so
          asset_name: libz3javalegacy.so
          asset_content_type: application/binary
      - name: upload com.microsoft.z3legacy.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/com.microsoft.z3legacy.jar
          asset_name: com.microsoft.z3legacy.jar
          asset_content_type: application/binary

  build-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'
      - run: |
          mkdir release
          python scripts/mk_make.py --prefix=$PWD/release --java
          cd build
          make -j $(nproc)
          make install 
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: release/
      - name: upload libz3legacy.dylib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/libz3legacy.dylib
          asset_name: libz3legacy.dylib
          asset_content_type: application/binary
      - name: upload libz3javalegacy.dylib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./build/libz3javalegacy.dylib
          asset_name: libz3javalegacy.dylib
          asset_content_type: application/binary