name: Windows

on:
  push:
    branches: [ master ]

jobs:               
  build:
    strategy:
      matrix:
        arch : [x64]
        include:
         - arch : x64
           bindings: -DZ3_BUILD_JAVA_BINDINGS=True
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - run: |
          md build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
          cmake ${{ matrix.bindings }} -G "NMake Makefiles" ../
          nmake    
          cd ..
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/
      - name: Run Regressions
        run: |
           git clone https://github.com/z3prover/z3test z3test
           python z3test\scripts\test_benchmarks.py build\z3.exe z3test\regressions\smt2
        shell: cmd
  

